variables:
  isReleaseMode: true
  buildWin32: true
  buildWin64: true
  OBSLatestTag: 26.1.2

trigger:
  branches:
    include:
      - master
      - main
      - just-notarize
  tags:
    include:
      - '*'

jobs:
- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.14'
  steps:
    - checkout: self
      submodules: true

    - task: InstallAppleCertificate@2
      displayName: 'Install release signing certificates'
      inputs:
        certSecureFile: 'Certificates.p12'
        certPwd: $(secrets.macOS.certificatesImportPassword)

    - script: ./ci/macos/notarize-packages.sh
      displayName: 'Package Plugin'
      env:
        URLs: $(URLs)
        RELEASE_MODE: True
        CODE_SIGNING_IDENTITY: $(secrets.macOS.codeSigningIdentity)
        INSTALLER_SIGNING_IDENTITY: $(secrets.macOS.installerSigningIdentity)
        AC_USERNAME: $(secrets.macOS.notarization.username)
        AC_PASSWORD: $(secrets.macOS.notarization.password)
        AC_PROVIDER_SHORTNAME: $(secrets.macOS.notarization.providerShortName)

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
